CLASS zcl_18_log_c326 DEFINITION INHERITING FROM zcl_16_log_c326
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: airplane_type REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_18_log_c326 IMPLEMENTATION.

  METHOD airplane_type.
     rv_airplane_type = 'Passenger Plane'.
  ENDMETHOD.

ENDCLASS.
